### ISSUE TITLE
It has bug when user win the game

### ISSUE THREAD

**Issue by wydxry** [cryer/monte-carlo-tree-search#2]
```Python
Traceback (most recent call last):
  File "E:/codes/pys/DynaQ/MCTS2/run.py", line 77, in <module>
    best_node = mcts.best_action(10)
  File "E:\codes\pys\DynaQ\MCTS2\mcts\search.py", line 14, in best_action
    return self.root.best_child(c_param=0.)
  File "E:\codes\pys\DynaQ\MCTS2\mcts\nodes.py", line 61, in best_child
    return self.children[np.argmax(choices_weights)]
  File "<__array_function__ internals>", line 6, in argmax
  File "C:\ProgramData\Anaconda3\envs\py37\lib\site-packages\numpy\core\fromnumeric.py", line 1195, in argmax
    return _wrapfunc(a, 'argmax', axis=axis, out=out)
  File "C:\ProgramData\Anaconda3\envs\py37\lib\site-packages\numpy\core\fromnumeric.py", line 54, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "C:\ProgramData\Anaconda3\envs\py37\lib\site-packages\numpy\core\fromnumeric.py", line 43, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
ValueError: attempt to get argmax of an empty sequence
    0   |   O       O       O    
    1   |   X       X       _    
    2   |   _       _       X    
______________________________
```

**Comment by wydxry** [comment]
ok, it can be deal add some code after file run.py line 75, like this
```Python
        board_state = TicTacToeGameState(state=c_board, next_to_move=1)
        root = MonteCarloTreeSearchNode(state=board_state, parent=None)

        if root.state.game_result == -1.0:
            print("You Win!")
            break

        mcts = MonteCarloTreeSearch(root)
        best_node = mcts.best_action(simulations_nums)
```
